
CREATE TABLE CF_AGENCIA (
    COD_EMPRESA   INTEGER NOT NULL,
    COD_AGENCIA   VARCHAR(8) NOT NULL,
    COD_BANCO     INTEGER NOT NULL,
    NOME_AGENCIA  VARCHAR(30),
    PRIMARY KEY (COD_EMPRESA, COD_AGENCIA, COD_BANCO)
);

CREATE TABLE CF_BANCO (
    COD_EMPRESA        INTEGER NOT NULL,
    COD_BANCO          INTEGER NOT NULL,
    NOME_BANCO         VARCHAR(30),
    AGENCIA_COD_BANCO  VARCHAR(10),
    AGENCIA_NOM_BANCO  VARCHAR(30),
    CONTA_NUM_BANCO    VARCHAR(10),
    CONTA_DESC_BANCO   VARCHAR(30),
    GERENTE_BANCO      VARCHAR(50),
    FONE1_BANCO        VARCHAR(15),
    FONE2_BANCO        VARCHAR(15),
    FONE3_BANCO        VARCHAR(15),
    PRIMARY KEY (COD_EMPRESA, COD_BANCO)
);

CREATE TABLE CF_CEDENTE (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CEDENTE           INTEGER NOT NULL,
    PESSOA_CEDENTE        VARCHAR(1),
    CARTEIRA_CEDENTE      VARCHAR(10),
    INSTRUCAO_CEDENTE     VARCHAR(250),
    CPFCNPJ_CEDENTE       VARCHAR(18),
    NOME_CEDENTE          VARCHAR(60),
    RUA_CEDENTE           VARCHAR(50),
    NUMERO_CEDENTE        VARCHAR(10),
    COMPL_CEDENTE         VARCHAR(20),
    BAIRRO_CEDENTE        VARCHAR(20),
    CIDADE_CEDENTE        VARCHAR(20),
    ESTADO_CEDENTE        VARCHAR(2),
    CEP_CEDENTE           VARCHAR(9),
    EMAIL_CEDENTE         VARCHAR(50),
    ULTIMO_NR_CEDENTE     VARCHAR(30),
    BANCO_CEDENTE         VARCHAR(10),
    AGENCIA_CEDENTE       VARCHAR(10),
    DIGITO_AG_CEDENTE     VARCHAR(2),
    CONTA_CEDENTE         VARCHAR(10),
    DIGITO_CTA_CEDENTE    VARCHAR(2),
    CODIGO_CEDENTE        VARCHAR(10),
    DIGITO_CEDENTE        VARCHAR(2),
    ULTIMO_NF_CEDENTE     VARCHAR(30),
    MENSALIDADE_SERV      VARCHAR(1),
    CODIGO_CEDENTE_BANCO  VARCHAR(20),
    PRIMARY KEY (COD_EMPRESA, COD_CEDENTE)
);

CREATE TABLE CF_CONFIG_SERV (
    COD_EMPRESA    INTEGER NOT NULL,
    COD_CONFIG     INTEGER NOT NULL,
    COD_SERV_IR    INTEGER,
    COD_SERV_RET   INTEGER,
    COD_SERV_MENS  INTEGER,
    VALOR_PISO_IR  NUMERIC(18,2),
    ALIQ_IR        NUMERIC(18,2),
    COD_SERV_CB    INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_CONFIG)
);

CREATE TABLE CF_CONTA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CONTA    VARCHAR(10) NOT NULL,
    COD_AGENCIA  VARCHAR(8),
    COD_BANCO    INTEGER,
    DESC_CONTA   VARCHAR(30),
    PRIMARY KEY (COD_EMPRESA, COD_CONTA)
);

CREATE TABLE CF_DESPESA_FIXA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_DESP_FIX         INTEGER NOT NULL,
    DESC_DESP_FIX        VARCHAR(40),
    ANOMES_DESP_FIX      VARCHAR(6),
    ANOMES_ATE_DESP_FIX  VARCHAR(6),
    DIA_VENCTO_DESP_FIX  VARCHAR(2),
    COD_PLCONTA          INTEGER,
    VALOR_DESP_FIX       NUMERIC(18,2),
    COD_CLIENTE          INTEGER,
    COD_BANCO            INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_DESP_FIX)
);

CREATE TABLE CF_GRUPO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_GRUPO      INTEGER NOT NULL,
    DESC_GRUPO     VARCHAR(30),
    COD_GRUPO_PAI  INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_GRUPO)
);

CREATE TABLE CF_IMP_NOTA (
    COD_EMPRESA           INTEGER NOT NULL,
    SEQ_IMP        INTEGER NOT NULL,
    CAMPO1         VARCHAR(30),
    CAMPO2         VARCHAR(30),
    POSX           SMALLINT,
    POSY           SMALLINT,
    TAMANHO_IMP    SMALLINT,
    TAMANHO_LINHA  SMALLINT,
    MASCARA        VARCHAR(50),
    TIPO_LETRA     VARCHAR(1),
    MUDA_LINHA     VARCHAR(1),
    TIPO_IMP       VARCHAR(1),
    TIPO_DADO      VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, SEQ_IMP)
);

CREATE TABLE CF_IMPOSTO (
    COD_EMPRESA           INTEGER NOT NULL,
    ANOMES_IMPOSTO        VARCHAR(6) NOT NULL,
    COD_IMPOSTO           INTEGER NOT NULL,
    COD_CLIENTE           INTEGER NOT NULL,
    NOME_IMPOSTO          VARCHAR(30),
    BASE_IMPOSTO          NUMERIC(18,2),
    VALOR_IMPOSTO         NUMERIC(18,2),
    DESCONTO_IMPOSTO      NUMERIC(18,2),
    JUROS_IMPOSTO         NUMERIC(18,2),
    MULTA_IMPOSTO         NUMERIC(18,2),
    DT_EMISSAO_IMPOSTO    TIMESTAMP,
    DT_VENCTO_IMPOSTO     TIMESTAMP,
    DESCRICAO_IMPOSTO     VARCHAR(200),
    DT_APURACAO_IMPOSTO   TIMESTAMP,
    ALIQ_IMPOSTO          NUMERIC(18,2),
    VALOR_IMPANT_IMPOSTO  NUMERIC(18,2),
    DT_PAGTO_IMPOSTO      TIMESTAMP,
    MODULO_IMPOSTO        VARCHAR(15),
    DCTF_IMPOSTO          VARCHAR(1),
    COD_USU               INTEGER,
    VARIACAO_IMPOSTO      INTEGER,
    CONFERIDO_IMPOSTO     VARCHAR(1),
    OBS_IMPOSTO           VARCHAR(40),
    PRIMARY KEY (COD_EMPRESA, ANOMES_IMPOSTO, COD_IMPOSTO, COD_CLIENTE)
);

CREATE TABLE CF_MOVIMENTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_MOVTO         INTEGER NOT NULL,
    COD_DESP_FIX      INTEGER,
    COD_PLCONTA       INTEGER,
    COMPL_HISTORICO   VARCHAR(20),
    NUMERO_DOCTO      VARCHAR(30),
    DT_VENCTO         TIMESTAMP,
    DT_EMISSAO        TIMESTAMP,
    DT_PAGTO          TIMESTAMP,
    VALOR_LANCTO      NUMERIC(18,2),
    VALOR_PAGO        NUMERIC(18,2),
    DESCONTO_MOVTO    NUMERIC(18,2),
    COD_CLIENTE       INTEGER,
    NR_NF             INTEGER,
    JUROS_MOVTO       NUMERIC(18,2),
    MULTA_MOVTO       NUMERIC(18,2),
    COD_BANCO         INTEGER,
    VALOR_IR_MOV      NUMERIC(18,2),
    ANOMES_MOVTO      VARCHAR(6),
    TIPO_BAIXA_MOVTO  VARCHAR(1),
    TIPO_COB_MOVTO    VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_MOVTO)
);

CREATE TABLE CF_MOVIMENTO_ITENS (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_MOVTO        INTEGER NOT NULL,
    COD_MOVTO_ITEM   INTEGER NOT NULL,
    COD_SERV         INTEGER,
    COMPL_ITEM       VARCHAR(50),
    VALOR_ITEM       NUMERIC(18,2),
    COMPL_HISTORICO  VARCHAR(50),
    COD_PLCONTA      INTEGER,
    INCIDE_IR_ITEM   VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_MOVTO, COD_MOVTO_ITEM)
);

CREATE TABLE CF_OBS_CLIENTE (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE  INTEGER NOT NULL,
    COD_OBS_CLI  INTEGER NOT NULL,
    DT_OBS_CLI   TIMESTAMP,
    OBS_CLI      VARCHAR(1000),
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, COD_OBS_CLI)
);

CREATE TABLE CF_PLANO_CONTA (
    COD_EMPRESA    INTEGER NOT NULL,
    COD_PLCONTA    INTEGER NOT NULL,
    DESC_PLCONTA   VARCHAR(40),
    TIPO_PLCONTA   VARCHAR(1),
    CONTA_DEBITO   VARCHAR(11),
    CONTA_CREDITO  VARCHAR(11),
    COD_GRUPO      INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_PLCONTA)
);

CREATE TABLE CF_PRE_LANCTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_PRE     INTEGER NOT NULL,
    TIPO_PRE    VARCHAR(1),
    CODIGO      INTEGER,
    ANOMES_PRE  VARCHAR(6),
    DT_LANCTO   TIMESTAMP,
    PRIMARY KEY (COD_EMPRESA, COD_PRE)
);

CREATE TABLE CF_SALDO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_BANCO     INTEGER NOT NULL,
    ANOMES_SALDO  VARCHAR(6) NOT NULL,
    VALOR_SALDO   NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_BANCO, ANOMES_SALDO)
);

CREATE TABLE CF_SERVICO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_SERV          INTEGER NOT NULL,
    DESC_SERV         VARCHAR(40),
    VALOR_SERV1       NUMERIC(18,2),
    VALOR_SERV2       NUMERIC(18,2),
    VALOR_SERV3       NUMERIC(18,2),
    VALOR_SERV4       NUMERIC(18,2),
    MENSALIDADE_SERV  VARCHAR(1),
    TIPO_SERV         VARCHAR(1),
    INCIDE_IRRF       VARCHAR(1),
    INCIDE_RET        VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_SERV)
);

CREATE TABLE CON_CONFIGURA (
    RAZAO_CON         VARCHAR(70) NOT NULL,
    ENDERECO_CON      VARCHAR(60),
    BAIRRO_CON        VARCHAR(20),
    CEP_CON           VARCHAR(9),
    CIDADE_CON        VARCHAR(20),
    ESTADO_CON        VARCHAR(2),
    EMAIL_CON         VARCHAR(50),
    TIPO_PESSOA_CON   VARCHAR(1),
    CPFCNPJ_CON       VARCHAR(14),
    FONE1_CON         VARCHAR(15),
    FONE2_CON         VARCHAR(15),
    FONE3_CON         VARCHAR(15),
    FONE4_CON         VARCHAR(15),
    FAX_CON           VARCHAR(15),
    FISCAL_CON        VARCHAR(1),
    CONTABIL_CON      VARCHAR(1),
    FOLHA_CON         VARCHAR(1),
    MASCARAPLANO_CON  VARCHAR(20),
    SPOOL_CON         VARCHAR(1),
    QTDE_USUARIO      INTEGER
);

CREATE TABLE EMISSAO_DOCTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE  INTEGER NOT NULL,
    COD_DOCTO    INTEGER NOT NULL,
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, COD_DOCTO)
);

CREATE TABLE GC_AGENDA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CONTATO      INTEGER NOT NULL,
    NOME_CONTATO     VARCHAR(40),
    EMPRESA_CONTATO  VARCHAR(40),
    EMAIL_CONTATO    VARCHAR(50),
    FONE1_CONTATO    VARCHAR(15),
    FONE2_CONTATO    VARCHAR(15),
    FONE3_CONTATO    VARCHAR(15),
    FONE4_CONTATO    VARCHAR(15),
    OBS_CONTATO      VARCHAR(255),
    COD_CLIENTE      INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_CONTATO)
);

CREATE TABLE GC_ASSUNTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_ASSUNTO        INTEGER NOT NULL,
    DESC_ASSUNTO       VARCHAR(250),
    COD_DEPTO          INTEGER,
    CLASSIFIC_ASSUNTO  VARCHAR(10),
    PRIMARY KEY (COD_EMPRESA, COD_ASSUNTO)
);

CREATE TABLE GC_ATENDIMENTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_ATENDIMENTO   INTEGER NOT NULL,
    COD_CLIENTE       INTEGER NOT NULL,
    DESCRICAO_ATEND   VARCHAR(3000),
    STATUS_ATEND      VARCHAR(1),
    PRIORIDADE_ATEND  VARCHAR(1),
    DT_ATEND          TIMESTAMP,
    TIPO_ATEND        VARCHAR(1),
    DT_COMPET_INI     TIMESTAMP,
    DT_COMPET_FIN     TIMESTAMP,
    DT_VENCTO         TIMESTAMP,
    VALOR_DOCTO       NUMERIC(18,2),
    COD_DOCTO         INTEGER,
    COD_DEPTO         INTEGER,
    NOME_CLIFUNC      VARCHAR(40),
    COD_FUNC          INTEGER,
    EMAIL_ATEND       VARCHAR(1),
    COBRA_ATEND       VARCHAR(1),
    RELATO_CLIENTE    TEXT,
    DT_PREV_FECHA     TIMESTAMP,
    INFORMADO_ATEND   VARCHAR(1),
    COD_ASSUNTO       INTEGER,
    DT_ALT_ATEND      TIMESTAMP,
    RESUMO_RELATO     VARCHAR(100),
    PRIMARY KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE)
);

CREATE TABLE GC_ATENDIMENTO_DOC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_DOC_ATEND    INTEGER NOT NULL,
    CAMINHO_DOC      VARCHAR(500),
    RESUMO_DOC       VARCHAR(1000),
    DT_DOC           TIMESTAMP,
    COD_CLIENTE      INTEGER,
    COD_ATENDIMENTO  INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_DOC_ATEND)
);

CREATE TABLE GC_ATENDIMENTO_PARC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_ATENDIMENTO  INTEGER NOT NULL,
    COD_CLIENTE      INTEGER NOT NULL,
    COD_PARCELA      INTEGER NOT NULL,
    COD_FUNC         INTEGER,
    DT_VENCTO_PARC   TIMESTAMP,
    VALOR_PARC       NUMERIC(18,2),
    OBS_PARC         VARCHAR(255),
    ENVIA_MEMO       VARCHAR(1),
    DT_PAGTO_PARC    TIMESTAMP,
    PRIMARY KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE, COD_PARCELA)
);

CREATE TABLE GC_ATENDIMENTO2 (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_ATENDIMENTO   INTEGER NOT NULL,
    COD_CLIENTE       INTEGER NOT NULL,
    DESCRICAO_ATEND   VARCHAR(1000),
    STATUS_ATEND      VARCHAR(1),
    PRIORIDADE_ATEND  VARCHAR(1),
    DT_ATEND          TIMESTAMP,
    TIPO_ATEND        VARCHAR(1),
    DT_COMPET_INI     TIMESTAMP,
    DT_COMPET_FIN     TIMESTAMP,
    DT_VENCTO         TIMESTAMP,
    VALOR_DOCTO       NUMERIC(18,2),
    COD_DOCTO         INTEGER,
    COD_DEPTO         INTEGER,
    NOME_CLIFUNC      VARCHAR(40),
    COD_FUNC          INTEGER,
    EMAIL_ATEND       VARCHAR(1),
    COBRA_ATEND       VARCHAR(1),
    RELATO_CLIENTE    TEXT,
    DT_PREV_FECHA     TIMESTAMP,
    INFORMADO_ATEND   VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE)
);

CREATE TABLE GC_CLIENTE (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE            INTEGER NOT NULL,
    COD_CLIENTE_ALT        INTEGER,
    CNPJCPF_CLI            VARCHAR(18),
    TIPO_CLI               VARCHAR(1),
    NOME_CLI               VARCHAR(50),
    FANTASIA_CLI           VARCHAR(50),
    ENDERECO_CLI           VARCHAR(50),
    END_COB_CLI            VARCHAR(60),
    COMPLEMENTO_CLI        VARCHAR(20),
    BAIRRO_CLI             VARCHAR(20),
    CIDADE_CLI             VARCHAR(20),
    UF_CLI                 VARCHAR(2),
    FONE1_CLI              VARCHAR(15),
    FONE2_CLI              VARCHAR(15),
    FONE3_CLI              VARCHAR(15),
    EMAIL_CLI              VARCHAR(50),
    CONTATO_CLI            VARCHAR(30),
    ATIVO_CLI              VARCHAR(1) NOT NULL,
    STATUS_CLI             VARCHAR(1),
    VALOR_MENSAL           NUMERIC(18,2),
    DIA_VENCTO             SMALLINT,
    CEP_CLI                VARCHAR(9),
    NIVEL_CLI              VARCHAR(1),
    COD_PLCONTA            INTEGER,
    TIPO_CLIFOR            VARCHAR(1),
    EMITE_NF_CLI           VARCHAR(1),
    COD_BANCO              INTEGER,
    BAIRRO_COB_CLI         VARCHAR(20),
    CIDADE_COB_CLI         VARCHAR(20),
    UF_COB_CLI             VARCHAR(2),
    CEP_COB_CLI            VARCHAR(9),
    CORRESPONDENCIA_CLI    VARCHAR(1),
    SENHA_INT              VARCHAR(15),
    TIPO_TAXA_CLI          VARCHAR(1),
    VALOR_TAXA_CLI         NUMERIC(18,2),
    MES_REF_CLI            VARCHAR(6),
    DATA_INICIO_CLI        TIMESTAMP,
    CCM_CLI                VARCHAR(20),
    IEST_CLI               VARCHAR(20),
    VALOR_ANT              NUMERIC(18,2),
    RET_PIS                VARCHAR(1),
    RET_COFINS             VARCHAR(1),
    RET_CSOCIAL            VARCHAR(1),
    DATA_FIM_CLI           TIMESTAMP,
    TAXA_BANCARIA_CLI      VARCHAR(1),
    CAPITAL_SOCIAL         NUMERIC(18,2),
    INTEGRALIZADO          NUMERIC(18,2),
    A_INTEGRALIZAR         NUMERIC(18,2),
    OBJETO_SOCIAL          VARCHAR(250),
    GERENCIA               VARCHAR(1),
    PRAZO                  VARCHAR(30),
    FORMA_INTEGRALIZAR     VARCHAR(1),
    BENS                   VARCHAR(255),
    ORGAO1                 VARCHAR(20),
    ORGAO2                 VARCHAR(20),
    ORGAO3                 VARCHAR(20),
    ORGAO4                 VARCHAR(20),
    ORGAO5                 VARCHAR(20),
    ORGAO6                 VARCHAR(20),
    ORGAO7                 VARCHAR(20),
    ORGAO8                 VARCHAR(20),
    SIGLA_CONSELHO         VARCHAR(20),
    TRIBUTACAO             VARCHAR(20),
    PREFEITURA             VARCHAR(20),
    OUTRA_TRIB             VARCHAR(20),
    OBS_CLI                VARCHAR(1000),
    TIPO_TRIB_CLI          VARCHAR(1),
    DIAMES_DECIMO_CLI      VARCHAR(4),
    QTD_FUNC               INTEGER,
    QTD_NF                 INTEGER,
    QTD_LANCTO_CTB         INTEGER,
    ANOMES_APU_INI         VARCHAR(6),
    ANOMES_APU_FIN         VARCHAR(6),
    RET_IRRF               VARCHAR(1),
    PAGINA_GUIA            VARCHAR(10),
    COD_SETOR              INTEGER,
    QTD_FUNC2              INTEGER,
    QTD_NF2                INTEGER,
    QTD_LANCTO_CTB2        INTEGER,
    PAGA13_CLI             VARCHAR(1),
    PROTESTA_CLI           VARCHAR(1),
    RET_13                 VARCHAR(1),
    RET_IR_13              VARCHAR(1),
    ENDERECO_DOC_CLI       VARCHAR(50),
    BAIRRO_DOC_CLI         VARCHAR(20),
    CIDADE_DOC_CLI         VARCHAR(20),
    UF_DOC_CLI             VARCHAR(2),
    CEP_DOC_CLI            VARCHAR(9),
    COD_CONTA              VARCHAR(10),
    ULTIMOANOMES_CONTABIL  VARCHAR(6),
    COD_USU_CTB            INTEGER,
    COD_USU_FIS            INTEGER,
    COD_USU_FOL            INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE)
);

CREATE TABLE GC_CLIENTE_FUNC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE    INTEGER NOT NULL,
    COD_CLI_FUNC   INTEGER NOT NULL,
    NOME_CLI_FUNC  VARCHAR(40),
    PRIMARY KEY (COD_EMPRESA, COD_CLI_FUNC)
);

CREATE TABLE GC_CLIENTE_REL (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE  INTEGER NOT NULL,
    COD_CLI_REL  INTEGER NOT NULL,
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, COD_CLI_REL)
);

CREATE TABLE GC_CLIENTE_SOC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE       INTEGER NOT NULL,
    COD_SOCIO         INTEGER NOT NULL,
    NOME_RAZAO        VARCHAR(50),
    CPF_CNPJ          VARCHAR(20),
    ORGAO_EMISSOR     VARCHAR(20),
    PROFISSAO         VARCHAR(20),
    ESTADO_CIVIL      VARCHAR(1),
    ORGAO_CLASSE      VARCHAR(20),
    VALOR_CAP_SOC     NUMERIC(18,2),
    PORC_CAP_SOC      NUMERIC(18,2),
    ENDERECO          VARCHAR(100),
    RG                VARCHAR(20),
    TITULO            VARCHAR(20),
    SEXO              VARCHAR(1),
    ORGAO_NUMERO      VARCHAR(30),
    PROCURADOR        VARCHAR(1),
    SITUACAO_SOC      VARCHAR(1),
    NUM_INSS_SOC      VARCHAR(20),
    TEMPO_INSS_SOC    VARCHAR(20),
    CONTRIB_ATU_INSS  VARCHAR(1),
    NUM_PIS_SOC       VARCHAR(20),
    EMAIL_SOC         VARCHAR(50),
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, COD_SOCIO)
);

CREATE TABLE GC_DEPARTAMENTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_DEPTO    INTEGER NOT NULL,
    DESC_DEPTO   VARCHAR(20),
    CUSTO_DEPTO  NUMERIC(18,2),
    TIPO_DEPTO   VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_DEPTO)
);

CREATE TABLE GC_DESCTAXA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_DESCTAXA   INTEGER NOT NULL,
    NOME_DESCTAXA  VARCHAR(20),
    PRIMARY KEY (COD_EMPRESA, COD_DESCTAXA)
);

CREATE TABLE GC_DOCUMENTO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_DOCTO          INTEGER NOT NULL,
    COD_DEPTO          INTEGER,
    DESC_DOCTO         VARCHAR(50),
    COMPETENCIA_DOCTO  VARCHAR(1),
    DIAS_DOCTO         INTEGER,
    STATUS_DIAS_DOCTO  VARCHAR(1),
    COD_SERV           INTEGER,
    COD_PLCONTA        INTEGER,
    COD_BANCO          INTEGER,
    DATA_VENCTO_DOCTO  TIMESTAMP,
    TIPO_VENCTO        VARCHAR(1),
    GERA_AGENDA        VARCHAR(1),
    DOC_ATIVO          VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_DOCTO)
);

CREATE TABLE GC_DOCUMENTO_EMITIDO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_PROTOCOLO    INTEGER NOT NULL,
    COD_DOCTO_EMI    INTEGER NOT NULL,
    COD_DOCTO        INTEGER NOT NULL,
    OBS_DOCTO_EMI    VARCHAR(30),
    DT_VENCIMENTO    TIMESTAMP,
    VALOR_DOCTO_EMI  NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_PROTOCOLO, COD_DOCTO_EMI)
);

CREATE TABLE GC_EMAIL (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_EMAIL       INTEGER NOT NULL,
    COD_FUNC        INTEGER,
    ASSUNTO_EMAIL   VARCHAR(255),
    DT_EMAIL        TIMESTAMP,
    CC_EMAIL        VARCHAR(255),
    TEXTO_EMAIL     VARCHAR(255),
    ARQUIVOS_EMAIL  VARCHAR(255),
    PRIMARY KEY (COD_EMPRESA, COD_EMAIL)
);

CREATE TABLE GC_EMAIL_CLI (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_EMAIL       INTEGER NOT NULL,
    EMAIL_CLI_CONT  INTEGER NOT NULL,
    COD_CLIENTE     INTEGER,
    COD_CONTATO     INTEGER,
    COD_SOCIO       INTEGER,
    PRIMARY KEY (COD_EMPRESA, EMAIL_CLI_CONT)
);

CREATE TABLE GC_ENTRADA_DOC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_ENTRADA       INTEGER NOT NULL,
    COD_CLIENTE       INTEGER NOT NULL,
    DT_ENTRADA        TIMESTAMP,
    DT_RETORNO        TIMESTAMP,
    ANOMES_COMPET     VARCHAR(6),
    COD_DOCTO         INTEGER,
    COMPL_DOCTO       VARCHAR(250),
    COD_DEPTO         INTEGER,
    OCORRECIA_ENT     VARCHAR(1000),
    COD_FUNC          INTEGER,
    CONTA_DEBITO      INTEGER,
    CONTA_CREDITO     INTEGER,
    VALOR_DOCTO       NUMERIC(18,2),
    EXPORTADO         VARCHAR(1),
    DIA_LANCTO        VARCHAR(2),
    HISTORICO_PADRAO  INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_ENTRADA, COD_CLIENTE)
);

CREATE TABLE GC_FERIADO (
    DT_FERIADO    TIMESTAMP NOT NULL,
    DESC_FERIADO  VARCHAR(30)
);

CREATE TABLE GC_FICHA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_FICHA           INTEGER NOT NULL,
    RAZAO1              VARCHAR(50),
    RAZAO2              VARCHAR(50),
    RAZAO3              VARCHAR(50),
    RAZAO_VALIDA1       VARCHAR(1),
    RAZAO_VALIDA2       VARCHAR(1),
    RAZAO_VALIDA3       VARCHAR(1),
    OBJETO_SOCIAL       VARCHAR(250),
    ENDERECO            VARCHAR(50),
    GERENCIA            VARCHAR(1),
    CONTATO             VARCHAR(30),
    FONE1               VARCHAR(15),
    FONE2               VARCHAR(15),
    CAPITAL_SOCIAL      NUMERIC(18,2),
    INTEGRALIZADO       NUMERIC(18,2),
    A_INTEGRALIZAR      NUMERIC(18,2),
    PRAZO               VARCHAR(30),
    FORMA_INTEGRALIZAR  VARCHAR(1),
    BENS                VARCHAR(255),
    VALOR_TAXA          NUMERIC(18,2),
    VALOR_SERVICO       NUMERIC(18,2),
    VALOR_OUTROS        NUMERIC(18,2),
    ORGAO1              VARCHAR(20),
    ORGAO2              VARCHAR(20),
    ORGAO3              VARCHAR(20),
    ORGAO4              VARCHAR(20),
    ORGAO5              VARCHAR(20),
    ORGAO6              VARCHAR(20),
    ORGAO7              VARCHAR(20),
    ORGAO8              VARCHAR(20),
    SIGLA_CONSELHO      VARCHAR(20),
    ALVARA_REGULAR      VARCHAR(1),
    PEDIDO_LICENCA      VARCHAR(1),
    TRIBUTACAO          VARCHAR(15),
    DT_CONTATO          TIMESTAMP,
    DT_INICIO           TIMESTAMP,
    DT_PREV_TERMINO     TIMESTAMP,
    DT_TERMINO          TIMESTAMP,
    OBS                 VARCHAR(1000),
    TIPO_PROCESSO       VARCHAR(1),
    OUTRA_TRIB          VARCHAR(20),
    COD_DEPTO           INTEGER,
    COD_FUNC            INTEGER,
    PREFEITURA          VARCHAR(20),
    ORGAO1_PROC         VARCHAR(1000),
    ORGAO2_PROC         VARCHAR(1000),
    ORGAO3_PROC         VARCHAR(1000),
    ORGAO4_PROC         VARCHAR(1000),
    ORGAO5_PROC         VARCHAR(1000),
    ORGAO6_PROC         VARCHAR(1000),
    ORGAO7_PROC         VARCHAR(1000),
    ORGAO8_PROC         VARCHAR(1000),
    COD_PLCONTA         INTEGER,
    COD_CLIENTE         INTEGER,
    COD_BANCO           INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_FICHA)
);

CREATE TABLE GC_FICHA_AND (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_FICHA       INTEGER NOT NULL,
    COD_ANDAMENTO   INTEGER NOT NULL,
    DT_ANDAMENTO    TIMESTAMP,
    DT_PREV_RET     TIMESTAMP,
    DT_FECHA        TIMESTAMP,
    DESC_ANDAMENTO  VARCHAR(1000),
    COD_FUNC        INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_FICHA, COD_ANDAMENTO)
);

CREATE TABLE GC_FICHA_PAG (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_FICHA    INTEGER NOT NULL,
    COD_PAG      INTEGER NOT NULL,
    DT_PREV_PAG  TIMESTAMP,
    DT_PAG       TIMESTAMP,
    VALOR_PAG    NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_FICHA, COD_PAG)
);

CREATE TABLE GC_FICHA_SOC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_FICHA         INTEGER NOT NULL,
    COD_SOCIO         INTEGER NOT NULL,
    NOME_RAZAO        VARCHAR(50),
    CPF_CNPJ          VARCHAR(20),
    ORGAO_EMISSOR     VARCHAR(20),
    PROFISSAO         VARCHAR(20),
    ESTADO_CIVIL      VARCHAR(1),
    ORGAO_CLASSE      VARCHAR(20),
    VALOR_CAP_SOC     NUMERIC(18,2),
    PORC_CAP_SOC      NUMERIC(18,2),
    ENDERECO          VARCHAR(100),
    RG                VARCHAR(20),
    TITULO            VARCHAR(20),
    SEXO              VARCHAR(1),
    ORGAO_NUMERO      VARCHAR(30),
    PROCURADOR        VARCHAR(1),
    SITUACAO_SOC      VARCHAR(1),
    NUM_INSS_SOC      VARCHAR(20),
    TEMPO_INSS_SOC    VARCHAR(20),
    CONTRIB_ATU_INSS  VARCHAR(1),
    NUM_PIS_SOC       VARCHAR(20),
    PRIMARY KEY (COD_EMPRESA, COD_FICHA, COD_SOCIO)
);

CREATE TABLE GC_FUNCIONARIO (
    COD_EMPRESA    INTEGER NOT NULL,
    COD_FUNC       INTEGER NOT NULL,
    COD_DEPTO      INTEGER,
    NOME_FUNC      VARCHAR(50),
    FONE1          VARCHAR(15),
    FONE2          VARCHAR(15),
    RESPONSAVEL    VARCHAR(20),
    EMAIL_FUNC     VARCHAR(50),
    APELIDO_FUNC   VARCHAR(50),
    SENHA_FUNC     VARCHAR(50),
    NIVEL_FUNC     VARCHAR(1),
    ATIVO_FUNC     VARCHAR(1),
    DT_NASCIMENTO  TIMESTAMP,
    RAMAL_FUNC     VARCHAR(5),
    VER_VALORES    VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_FUNC)
);

CREATE TABLE GC_LEMBRETE (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_AGENDA        INTEGER NOT NULL,
    COD_FUNC          INTEGER NOT NULL,
    ASSUNTO_AGENDA    VARCHAR(100),
    RELATO_AGENDA     TEXT,
    DT_AGENDA         TIMESTAMP,
    DT_MOSTRA_AGENDA  TIMESTAMP,
    STATUS_AGENDA     VARCHAR(1),
    DT_FECHA_AGENDA   TIMESTAMP,
    PRIMARY KEY (COD_EMPRESA, COD_AGENDA, COD_FUNC)
);

CREATE TABLE GC_LIGACAO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_LIGACAO        INTEGER NOT NULL,
    COD_CLIENTE        INTEGER,
    COD_CONTATO        INTEGER,
    COD_FUNC           INTEGER,
    COD_DEPTO          INTEGER,
    DESC_LIG           VARCHAR(1000),
    PRIORIDADE_LIG     VARCHAR(1),
    STATUS_LIG         VARCHAR(1),
    DT_PEDIDO_LIG      TIMESTAMP NOT NULL,
    DT_FECHAMENTO_LIG  TIMESTAMP,
    FONE1              VARCHAR(15),
    FONE2              VARCHAR(15),
    FONE3              VARCHAR(15),
    FONE4              VARCHAR(15),
    CONTATO            VARCHAR(50),
    RAMAL1             VARCHAR(4),
    RAMAL2             VARCHAR(4),
    RAMAL3             VARCHAR(4),
    RAMAL4             VARCHAR(4),
    COD_FUNC_CAD       INTEGER,
    OBS_LIG            VARCHAR(1000),
    QUEMFALA           VARCHAR(1),
    TIPO_LIGACAO       VARCHAR(1),
    INFORMADO_LIG      VARCHAR(1),
    PARTICULAR_LIG     VARCHAR(1),
    COD_ASSUNTO        INTEGER,
    COD_ATENDIMENTO    INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_LIGACAO)
);

CREATE TABLE GC_LIVRO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_LIVRO     INTEGER NOT NULL,
    DESC_LIVRO    VARCHAR(50),
    VALOR1_LIVRO  NUMERIC(18,2),
    VALOR2_LIVRO  NUMERIC(18,2),
    VALOR3_LIVRO  NUMERIC(18,2),
    VALOR4_LIVRO  NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_LIVRO)
);

CREATE TABLE GC_LIVRO_OCORRENCIA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE   INTEGER NOT NULL,
    COD_LIVRO     INTEGER NOT NULL,
    NR_LIVRO      INTEGER NOT NULL,
    ENCADERNADO   VARCHAR(1),
    DT_ENT_ENC    TIMESTAMP,
    DT_RET_ENC    TIMESTAMP,
    ASSINATURA    VARCHAR(1),
    DT_ENT_ASS    TIMESTAMP,
    DT_RET_ASS    TIMESTAMP,
    REGISTRO      VARCHAR(1),
    DT_ENT_REG    TIMESTAMP,
    DT_RET_REG    TIMESTAMP,
    NR_REGISTRO   VARCHAR(20),
    CLIENTE       VARCHAR(1),
    DT_ENT_CLI    TIMESTAMP,
    DT_RET_CLI    TIMESTAMP,
    NR_PROTOCOLO  VARCHAR(20),
    OBS_LIVRO     VARCHAR(200),
    QTD_LIVRO     INTEGER,
    VALOR_LIVRO   NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, COD_LIVRO, NR_LIVRO)
);

CREATE TABLE GC_MEMORANDO (
    COD_EMPRESA           INTEGER NOT NULL,
    ASSUNTO_MEMO     VARCHAR(100),
    RELATO_MEMO      TEXT,
    COD_MEMO         INTEGER NOT NULL,
    DT_MEMO          TIMESTAMP,
    STATUS_MEMO      VARCHAR(1),
    DT_FECHA_MEMO    TIMESTAMP,
    COD_FUNC         INTEGER,
    GRAU_MEMO        VARCHAR(1),
    COD_CLIENTE      INTEGER,
    COD_ATENDIMENTO  INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_MEMO)
);

CREATE TABLE GC_MEMORANDO_FUNC (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_FUNC          INTEGER NOT NULL,
    COD_MEMO          INTEGER NOT NULL,
    STATUS_MEMO_FUNC  VARCHAR(1),
    DT_FECHA_MEMO     TIMESTAMP,
    PRIMARY KEY (COD_EMPRESA, COD_FUNC, COD_MEMO)
);

CREATE TABLE GC_MENSALIDADE_CLI (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE        INTEGER NOT NULL,
    DT_ALTERACAO       TIMESTAMP NOT NULL,
    VALOR_MENSALIDADE  NUMERIC(18,2),
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, DT_ALTERACAO)
);

CREATE TABLE GC_OBRIGACOES (
    COD_EMPRESA    INTEGER NOT NULL,
    COD_OBR        INTEGER NOT NULL,
    ANOMES_OBR     VARCHAR(6) NOT NULL,
    COD_CLIENTE    INTEGER NOT NULL,
    COD_DOCTO      INTEGER,
    DT_VENCTO      TIMESTAMP,
    DT_ENVIO       TIMESTAMP,
    MEIO_ENVIO     VARCHAR(1),
    VALOR_DOCTO    NUMERIC(18,2),
    OBS_OBRIGACAO  VARCHAR(1000),
    PRIMARY KEY (COD_EMPRESA, COD_OBR, ANOMES_OBR, COD_CLIENTE)
);

CREATE TABLE GC_OCORRENCIA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_OCORRENCIA       INTEGER NOT NULL,
    COD_ATENDIMENTO      INTEGER NOT NULL,
    COD_CLIENTE          INTEGER NOT NULL,
    COD_FUNC             INTEGER,
    DT_OCORRENCIA        TIMESTAMP NOT NULL,
    STATUS_OCORR         VARCHAR(1),
    COD_FUNC_TRANS       INTEGER,
    DT_FECHAMENTO_OCORR  TIMESTAMP,
    DESCRICAO_OCORR      VARCHAR(255),
    PRIMARY KEY (COD_EMPRESA, COD_OCORRENCIA)
);

CREATE TABLE GC_OCORRENCIA2 (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_OCORRENCIA       INTEGER NOT NULL,
    COD_ATENDIMENTO      INTEGER NOT NULL,
    COD_CLIENTE          INTEGER NOT NULL,
    COD_FUNC             INTEGER,
    DT_OCORRENCIA        TIMESTAMP NOT NULL,
    STATUS_OCORR         VARCHAR(1),
    COD_FUNC_TRANS       INTEGER,
    DT_FECHAMENTO_OCORR  TIMESTAMP,
    DESCRICAO_OCORR      VARCHAR(255),
    PRIMARY KEY (COD_EMPRESA, COD_OCORRENCIA)
);

CREATE TABLE GC_PROTOCOLO (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_PROTOCOLO      INTEGER NOT NULL,
    COD_CLIENTE        INTEGER NOT NULL,
    OBS_PROTOCOLO      VARCHAR(1000),
    DT_EMISSAO_PROTO   TIMESTAMP,
    DT_ENTREGA_PREV    TIMESTAMP,
    DT_ENTREGA_PROTO   TIMESTAMP,
    STATUS_ENTREGA     VARCHAR(1),
    COD_FUNC           INTEGER,
    COD_FUNC_CAD       INTEGER,
    RESPONSAVEL_PROTO  VARCHAR(30),
    ASSINATURA_PROTO   TEXT,
    COD_ATENDIMENTO    INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_PROTOCOLO)
);

CREATE TABLE GC_SETOR (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_SETOR   INTEGER NOT NULL,
    DESC_SETOR  VARCHAR(50),
    GERA_PROTO  VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, COD_SETOR)
);

CREATE TABLE GC_TAXA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_CLIENTE      INTEGER NOT NULL,
    NOME_TAXA        VARCHAR(20) NOT NULL,
    VALOR_TAXA       NUMERIC(18,2),
    REF_TAXA         VARCHAR(10),
    TIPO_TAXA        VARCHAR(1),
    INCIDENCIA_TAXA  VARCHAR(1),
    QTDE_BENS        INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_CLIENTE, NOME_TAXA)
);

CREATE TABLE GC_VISITA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_VISITA        INTEGER NOT NULL,
    COD_FUNC          INTEGER NOT NULL,
    DT_VISITA         TIMESTAMP NOT NULL,
    DT_PREV_RET       TIMESTAMP,
    MOTIVO_VISITA     VARCHAR(1000),
    OBS_VISITA        VARCHAR(1000),
    CONTATO_VISITA    VARCHAR(50) NOT NULL,
    STATUS_VISITA     VARCHAR(1),
    COD_FUNC_CAD_VIS  INTEGER,
    TIPO_COMPROMISSO  VARCHAR(1),
    DETALHE_VISTA     VARCHAR(1000),
    COD_CLIENTE       INTEGER,
    INFORMADO_VIS     VARCHAR(1),
    COD_ATENDIMENTO   INTEGER,
    PRIMARY KEY (COD_EMPRESA, COD_VISITA, COD_FUNC)
);

CREATE TABLE INT_PESQUISA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_PESQUISA  INTEGER NOT NULL,
    RETORNO       VARCHAR(1),
    RESOLUCAO     VARCHAR(1),
    ATENDIMENTO   VARCHAR(1),
    CRITICA       VARCHAR(255),
    EMAIL         VARCHAR(100),
    DATA          TIMESTAMP,
    PRIMARY KEY (COD_EMPRESA, COD_PESQUISA)
);

CREATE TABLE INT_SISTEMA (
    COD_EMPRESA           INTEGER NOT NULL,
    COD_SISTEMA      INTEGER NOT NULL,
    NOME_SISTEMA     VARCHAR(30),
    CAMINHO_SISTEMA  VARCHAR(100),
    DESC_SISTEMA     VARCHAR(250),
    PRIMARY KEY (COD_EMPRESA, COD_SISTEMA)
);

CREATE TABLE INT_SISTEMA_CLI (
    COD_EMPRESA           INTEGER NOT NULL,
    CODIGO_CLI     INTEGER NOT NULL,
    COD_SISTEMA    INTEGER NOT NULL,
    AUTORIZA_DOWN  VARCHAR(1),
    PRIMARY KEY (COD_EMPRESA, CODIGO_CLI, COD_SISTEMA)
);

CREATE TABLE MENU (
    MENU       INTEGER NOT NULL,
    DESCRICAO  VARCHAR(50),
    ORDEM      INTEGER
);

CREATE TABLE MENU_SUB (
    MENU       INTEGER NOT NULL,
    SUB        INTEGER NOT NULL,
    DESCRICAO  VARCHAR(50),
    ARQUIVO    VARCHAR(100),
    ORDEM      INTEGER,
    PAGINA     VARCHAR(100)
);

CREATE TABLE PAGINA (
    PAGINA     INTEGER NOT NULL,
    CODIGO     INTEGER NOT NULL,
    DESCRICAO  VARCHAR(50),
    HTML       VARCHAR(255)
);

CREATE TABLE SEG_LIBERA (
    LIBERA         VARCHAR(50) NOT NULL,
    ULTIMO_SCRIPT  VARCHAR(30),
    STATUS         VARCHAR(1)
);

/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CF_AGENCIA        ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_CONTA          ADD FOREIGN KEY (COD_EMPRESA, COD_AGENCIA, COD_BANCO) REFERENCES CF_AGENCIA (COD_EMPRESA, COD_AGENCIA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_DESPESA_FIXA   ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_GRUPO          ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO          ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_GRUPO         ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO_PAI) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_DESP_FIX) REFERENCES CF_DESPESA_FIXA (COD_EMPRESA, COD_DESP_FIX);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO     ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_MOVTO) REFERENCES CF_MOVIMENTO (COD_EMPRESA, COD_MOVTO);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_MOVIMENTO_ITENS ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_OBS_CLIENTE     ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE CF_PLANO_CONTA     ADD FOREIGN KEY (COD_EMPRESA, COD_GRUPO) REFERENCES CF_GRUPO (COD_EMPRESA, COD_GRUPO);
ALTER TABLE EMISSAO_DOCTO       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE EMISSAO_DOCTO       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_CLIENTE           ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_CLIENTE_FUNC ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLI_REL) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_REL       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_CLIENTE_SOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_SERV) REFERENCES CF_SERVICO (COD_EMPRESA, COD_SERV);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_DOCUMENTO         ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_DOCUMENTO_EMITIDO ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_EMAIL             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_EMAIL_CLI         ADD FOREIGN KEY (COD_EMPRESA, COD_CONTATO) REFERENCES GC_AGENDA (COD_EMPRESA, COD_CONTATO);
ALTER TABLE GC_EMAIL_CLI         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_EMAIL_CLI         ADD FOREIGN KEY (COD_EMPRESA, COD_EMAIL) REFERENCES GC_EMAIL (COD_EMPRESA, COD_EMAIL);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_ENTRADA_DOC       ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_PLCONTA) REFERENCES CF_PLANO_CONTA (COD_EMPRESA, COD_PLCONTA);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_FICHA             ADD FOREIGN KEY (COD_EMPRESA, COD_BANCO) REFERENCES CF_BANCO (COD_EMPRESA, COD_BANCO);
ALTER TABLE GC_FICHA_AND         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_AND         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_PAG         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FICHA_SOC         ADD FOREIGN KEY (COD_EMPRESA, COD_FICHA) REFERENCES GC_FICHA (COD_EMPRESA, COD_FICHA);
ALTER TABLE GC_FUNCIONARIO       ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_LIGACAO           ADD FOREIGN KEY (COD_EMPRESA, COD_CONTATO) REFERENCES GC_AGENDA (COD_EMPRESA, COD_CONTATO);
ALTER TABLE GC_LIGACAO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_LIGACAO           ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_LIGACAO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_LIGACAO           ADD FOREIGN KEY (COD_EMPRESA, COD_DEPTO) REFERENCES GC_DEPARTAMENTO (COD_EMPRESA, COD_DEPTO);
ALTER TABLE GC_MEMORANDO_FUNC    ADD FOREIGN KEY (COD_EMPRESA, COD_MEMO) REFERENCES GC_MEMORANDO (COD_EMPRESA, COD_MEMO);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_MENSALIDADE_CLI   ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_OBRIGACOES         ADD FOREIGN KEY (COD_EMPRESA, COD_DOCTO) REFERENCES GC_DOCUMENTO (COD_EMPRESA, COD_DOCTO);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_OCORRENCIA         ADD FOREIGN KEY (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE) REFERENCES GC_ATENDIMENTO (COD_EMPRESA, COD_ATENDIMENTO, COD_CLIENTE);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_PROTOCOLO           ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_TAXA                 ADD FOREIGN KEY (COD_EMPRESA, COD_CLIENTE) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);
ALTER TABLE GC_VISITA               ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE GC_VISITA               ADD FOREIGN KEY (COD_EMPRESA, COD_FUNC_CAD_VIS) REFERENCES GC_FUNCIONARIO (COD_EMPRESA, COD_FUNC);
ALTER TABLE INT_SISTEMA_CLI         ADD FOREIGN KEY (COD_EMPRESA, COD_SISTEMA) REFERENCES INT_SISTEMA (COD_EMPRESA, COD_SISTEMA);
ALTER TABLE INT_SISTEMA_CLI         ADD FOREIGN KEY (COD_EMPRESA, CODIGO_CLI) REFERENCES GC_CLIENTE (COD_EMPRESA, COD_CLIENTE);



