ALTER TABLE GC_FICHA ADD "COD_DEPTO" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD "COD_FUNC" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD "PREFEITURA" VARCHAR(20);

ALTER TABLE GC_FICHA ADD "ORGAO1_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO2_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO3_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO4_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO5_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO6_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO7_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO8_PROC" VARCHAR(1000);

ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_DEPTO") REFERENCES GC_DEPARTAMENTO;
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_FUNC") REFERENCES GC_FUNCIONARIO;

ALTER TABLE GC_FICHA_SOC ALTER "ENDERECO" TYPE VARCHAR(100);
ALTER TABLE GC_FICHA_SOC ADD "SEXO" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "ORGAO_NUMERO" VARCHAR(30);
ALTER TABLE GC_FICHA_SOC ADD "PROCURADOR" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "SITUACAO_SOC" VARCHAR(1);

ALTER TABLE GC_VISITA ADD "TIPO_COMPROMISSO" VARCHAR(1);

ALTER TABLE GC_PROTOCOLO ADD "COD_FUNC_CAD" NUMERIC(9,0);
ALTER TABLE GC_PROTOCOLO ADD FOREIGN KEY ("COD_FUNC_CAD") REFERENCES GC_FUNCIONARIO ("COD_FUNC");

ALTER TABLE GC_DOCUMENTO_EMITIDO ADD "DT_VENCIMENTO" TIMESTAMP;


ALTER TABLE GC_VISITA  ADD "DETALHE_VISTA" VARCHAR(1000);
ALTER TABLE GC_LIGACAO ADD "TIPO_LIGACAO" VARCHAR(1);
DROP TRIGGER "TRI_GEN_ATEND";

/* 26 de agosto 2002 */
ALTER TABLE "GC_CLIENTE"   ADD "NIVEL_CLI" VARCHAR(1);
ALTER TABLE GC_CLIENTE ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_CLIENTE ADD "COD_CONTA"	VARCHAR(10);
ALTER TABLE GC_CLIENTE ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_CLIENTE ADD FOREIGN KEY ("COD_CONTA") REFERENCES CF_CONTA ("COD_CONTA");

ALTER TABLE GC_DOCUMENTO ADD "COD_SERV"	NUMERIC(9,0);
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_SERV") REFERENCES CF_SERVICO ("COD_SERV");

ALTER TABLE GC_DOCUMENTO ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_DOCUMENTO ADD "COD_CONTA"   VARCHAR(10);
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_CONTA")   REFERENCES CF_CONTA ("COD_CONTA");

/* 28 de agosto 2002 */
CREATE TABLE "GC_FICHA_PAG"
(
  "COD_FICHA"	   NUMERIC(9, 0) NOT NULL,
  "COD_PAG"        NUMERIC(9, 0) NOT NULL,
  "DT_PREV_PAG"    TIMESTAMP,
  "DT_PAG"         TIMESTAMP,
  "VALOR_PAG"	   DOUBLE PRECISION,
  PRIMARY KEY ("COD_FICHA", "COD_PAG")
);
ALTER TABLE "GC_FICHA_PAG" ADD FOREIGN KEY ("COD_FICHA") REFERENCES GC_FICHA ("COD_FICHA");

ALTER TABLE GC_FICHA ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_FICHA ADD "COD_CONTA"   VARCHAR(10);
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_CONTA")   REFERENCES CF_CONTA ("COD_CONTA");

/* 29 de agosto 2002 */
ALTER TABLE GC_DOCUMENTO ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_CLIENTE ADD "TIPO_CLIFOR" VARCHAR(1);

/* 03 de Setembro */
ALTER TABLE GC_FICHA ADD "COD_CLIENTE" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE;

/* 04 de Outubro */
ALTER TABLE GC_FUNCIONARIO ADD "ATIVO_FUNC" VARCHAR(1);

/* 30 de Outubro */
ALTER TABLE GC_ATENDIMENTO ADD "EMAIL_ATEND" VARCHAR(1);
ALTER TABLE GC_ATENDIMENTO ADD "COBRA_ATEND" VARCHAR(1);

/* 12 DE NOVEMBRO */
/*alter table GC_VISITA DROP "COD_CLIENTE";*/
alter table GC_VISITA add "COD_CLIENTE" numeric(9,0);
ALTER TABLE "GC_VISITA" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");

/* 20 DE NOVEMBRO */
ALTER TABLE GC_FICHA_SOC ADD "NUM_INSS_SOC" VARCHAR(20);
ALTER TABLE GC_FICHA_SOC ADD "TEMPO_INSS_SOC" VARCHAR(20);
ALTER TABLE GC_FICHA_SOC ADD "CONTRIB_ATU_INSS" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "NUM_PIS_SOC" VARCHAR(20);

/* 26 DE NOVEMBRO */
ALTER TABLE GC_ATENDIMENTO ADD "RELATO_CLIENTE" BLOB;
ALTER TABLE GC_ATENDIMENTO ADD "DT_PREV_FECHA" TIMESTAMP;

/* 27 DE NOVEMBRO */
ALTER TABLE GC_ATENDIMENTO ADD "INFORMADO_ATEND" VARCHAR(1);
ALTER TABLE GC_VISITA ADD "INFORMADO_VIS" VARCHAR(1);
ALTER TABLE GC_LIGACAO ADD "INFORMADO_LIG" VARCHAR(1);

UPDATE GC_ATENDIMENTO SET INFORMADO_ATEND='N';
UPDATE GC_VISITA      SET INFORMADO_VIS='N';
UPDATE GC_LIGACAO     SET INFORMADO_LIG='N';

/* 21 DE DEZEMBRO 2003*/
ALTER TABLE GC_FUNCIONARIO ADD "DT_NASCIMENTO" TIMESTAMP;

/* 20 DE MARÇO 2003*/
ALTER TABLE GC_CLIENTE ADD "BAIRRO_COB_CLI" VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "CIDADE_COB_CLI" VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "UF_COB_CLI"     VARCHAR(2);
ALTER TABLE GC_CLIENTE ADD "CEP_COB_CLI"    VARCHAR(9);
ALTER TABLE GC_CLIENTE ADD "CORRESPONDENCIA_CLI" VARCHAR(1);

/* 30 DE MARÇO 2003*/
ALTER TABLE GC_CLIENTE   ADD "TIPO_TAXA_CLI"  VARCHAR(1);
ALTER TABLE GC_CLIENTE   ADD "VALOR_TAXA_CLI" DOUBLE PRECISION;
ALTER TABLE GC_DOCUMENTO ADD "DATA_VENCTO_DOCTO" TIMESTAMP;

/* 02 DE JULHO 2003*/
ALTER TABLE GC_CLIENTE   ADD "MES_REF_CLI"  VARCHAR(6);
ALTER TABLE GC_CLIENTE   ADD "DATA_INICIO_CLI"  TIMESTAMP;

/* 11 DE JULHO 2003*/
CREATE TABLE "GC_ATENDIMENTO_PARC"
(
  "COD_ATENDIMENTO"	NUMERIC(9, 0) NOT NULL,
  "COD_CLIENTE"	    NUMERIC(9, 0) NOT NULL,
  "COD_PARCELA"	    NUMERIC(9, 0) NOT NULL,
  "COD_FUNC"	      NUMERIC(9, 0),
  "DT_VENCTO_PARC"	TIMESTAMP,
  "VALOR_PARC"      DOUBLE PRECISION,
  "OBS_PARC"	      VARCHAR(255),
  PRIMARY KEY ("COD_ATENDIMENTO","COD_CLIENTE","COD_PARCELA")
);
ALTER TABLE "GC_OCORRENCIA" ADD FOREIGN KEY ("COD_FUNC") REFERENCES GC_FUNCIONARIO;
ALTER TABLE "GC_OCORRENCIA" ADD FOREIGN KEY ("COD_ATENDIMENTO", "COD_CLIENTE") REFERENCES GC_ATENDIMENTO ("COD_ATENDIMENTO", "COD_CLIENTE");

/* 23 DE JUNHO 2003 */
ALTER TABLE GC_CLIENTE ADD "SENHA_INT" VARCHAR(15);

/* 10 DE JULHO 2003 */
ALTER TABLE GC_DOCUMENTO_EMITIDO ADD "VALOR_DOCTO_EMI" DOUBLE PRECISION;

/* 07 DE AGOSTO 2003 */
ALTER TABLE "GC_PROTOCOLO" ADD "RESPONSAVEL_PROTO" VARCHAR(30);

/* 27 DE AGOSTO 2003 */
ALTER TABLE "GC_FUNCIONARIO" ADD "RAMAL_FUNC" VARCHAR(5);

alter table GC_CLIENTE ADD "EMITE_NF_CLI" VARCHAR(1);

/* 22 de Março de 2003 */
CREATE TABLE CF_CEDENTE (
  COD_CEDENTE NUMERIC(9,0) NOT NULL,
  PESSOA_CEDENTE VARCHAR(1),
  CARTEIRA_CEDENTE VARCHAR(7),
  INSTRUCAO_CEDENTE VARCHAR(250),
  CPFCNPJ_CEDENTE   VARCHAR(18),
  NOME_CEDENTE      VARCHAR(60),
  RUA_CEDENTE       VARCHAR(50),
  NUMERO_CEDENTE    VARCHAR(10),
  COMPL_CEDENTE     VARCHAR(20),
  BAIRRO_CEDENTE    VARCHAR(20),
  CIDADE_CEDENTE    VARCHAR(20),
  ESTADO_CEDENTE    VARCHAR(2),
  CEP_CEDENTE       VARCHAR(9),
  EMAIL_CEDENTE     VARCHAR(50),
  ULTIMO_NR_CEDENTE VARCHAR(30),
  BANCO_CEDENTE     VARCHAR(10),
  AGENCIA_CEDENTE   VARCHAR(10),
  DIGITO_AG_CEDENTE VARCHAR(2),
  CONTA_CEDENTE     VARCHAR(10),
  DIGITO_CTA_CEDENTE VARCHAR(2),
  CODIGO_CEDENTE     VARCHAR(10),
  DIGITO_CEDENTE     VARCHAR(2),
  PRIMARY KEY (COD_CEDENTE)
);

/* 25 de Março de 2003 */
ALTER TABLE CF_SERVICO ADD "MENSALIDADE_SERV" VARCHAR(1);

/* 26 de Março de 2003 */
ALTER TABLE CF_CEDENTE   ADD "ULTIMO_NF_CEDENTE" VARCHAR(30);
ALTER TABLE GC_CLIENTE   ADD "EMITE_NF_CLI"      VARCHAR(1);
ALTER TABLE CF_MOVIMENTO ADD "NR_NF"             NUMERIC(9, 0);
ALTER TABLE CF_MOVIMENTO ADD "JUROS_MOVTO"       DOUBLE PRECISION;
ALTER TABLE CF_MOVIMENTO ADD "MULTA_MOVTO"       DOUBLE PRECISION;

CREATE TABLE "CF_IMP_NOTA"
(
  "SEQ_IMP"	      NUMERIC(9, 0) NOT NULL,
  "CAMPO1"	      VARCHAR(30),
  "CAMPO2"	      VARCHAR(30),
  "POSX"	        NUMERIC(4, 0),
  "POSY"	        NUMERIC(4, 0),
  "TAMANHO_IMP"	  NUMERIC(4, 0),
  "TAMANHO_LINHA"	NUMERIC(4, 0),
  "MASCARA"	      VARCHAR(50),
  "TIPO_LETRA"	  VARCHAR(1),
  "MUDA_LINHA"	  VARCHAR(1),
  "TIPO_IMP"      VARCHAR(1),
  "TIPO_DADO"     VARCHAR(1),
  PRIMARY KEY ("SEQ_IMP")
);

CREATE TABLE "CF_GRUPO"
(
  "COD_GRUPO"	      NUMERIC(9, 0) NOT NULL,
  "DESC_GRUPO"      VARCHAR(30),
  PRIMARY KEY ("COD_GRUPO")
);
ALTER TABLE CF_PLANO_CONTA ADD "COD_GRUPO" NUMERIC(9,0);
ALTER TABLE CF_PLANO_CONTA ADD FOREIGN KEY ("COD_GRUPO" ) REFERENCES "CF_GRUPO";

/* 27 de Março de 2003 */
ALTER TABLE "CF_BANCO" ADD "AGENCIA_COD_BANCO"	VARCHAR(10);
ALTER TABLE "CF_BANCO" ADD "AGENCIA_NOM_BANCO"	VARCHAR(30);
ALTER TABLE "CF_BANCO" ADD "CONTA_NUM_BANCO"	  VARCHAR(10);
ALTER TABLE "CF_BANCO" ADD "CONTA_DESC_BANCO"	  VARCHAR(30);
ALTER TABLE "CF_BANCO" ADD "GERENTE_BANCO"	    VARCHAR(50);
ALTER TABLE "CF_BANCO" ADD "FONE1_BANCO"	      VARCHAR(15);
ALTER TABLE "CF_BANCO" ADD "FONE2_BANCO"	      VARCHAR(15);
ALTER TABLE "CF_BANCO" ADD "FONE3_BANCO"	      VARCHAR(15);

DROP TABLE "CF_SALDO";

CREATE TABLE "CF_SALDO" 
(
  "COD_BANCO"	NUMERIC(9, 0) NOT NULL,
  "ANOMES_SALDO"	VARCHAR(6) NOT NULL,
  "VALOR_SALDO"	DOUBLE PRECISION,
 PRIMARY KEY ("COD_BANCO", "ANOMES_SALDO")
);
ALTER TABLE "CF_SALDO" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

ALTER TABLE "CF_DESPESA_FIXA" DROP "COD_CONTA";
ALTER TABLE "CF_DESPESA_FIXA" ADD "COD_BANCO"	NUMERIC(9, 0);
ALTER TABLE "CF_DESPESA_FIXA" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

DROP INDEX XIF3CF_MOVIMENTO;
ALTER TABLE "CF_MOVIMENTO" DROP "COD_CONTA";
ALTER TABLE "CF_MOVIMENTO" ADD "COD_BANCO"	NUMERIC(9, 0);
ALTER TABLE "CF_MOVIMENTO" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

ALTER TABLE "GC_CLIENTE" DROP "COD_CONTA";
ALTER TABLE "GC_CLIENTE" ADD "COD_BANCO"	NUMERIC(9, 0);
ALTER TABLE "GC_CLIENTE" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

ALTER TABLE "GC_DOCUMENTO" DROP "COD_CONTA";
ALTER TABLE "GC_DOCUMENTO" ADD "COD_BANCO"	NUMERIC(9, 0);
ALTER TABLE "GC_DOCUMENTO" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

ALTER TABLE "GC_FICHA" DROP "COD_CONTA";
ALTER TABLE "GC_FICHA" ADD "COD_BANCO"	NUMERIC(9, 0);
ALTER TABLE "GC_FICHA" ADD FOREIGN KEY ("COD_BANCO") REFERENCES CF_BANCO ("COD_BANCO");

ALTER TABLE "CF_MOVIMENTO_ITENS" ADD "COMPL_HISTORICO"	VARCHAR(20);
ALTER TABLE "CF_MOVIMENTO_ITENS" ADD "COD_PLCONTA"	NUMERIC(9, 0);
ALTER TABLE "CF_MOVIMENTO_ITENS" ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");

/* 08 de Abril de 2003 */
ALTER TABLE "CF_CEDENTE" ALTER "CARTEIRA_CEDENTE"	TYPE VARCHAR(10);

/* 23 de Julho de 2003 */
ALTER TABLE "CF_GRUPO" ADD "COD_GRUPO_PAI" NUMERIC(9,0);
ALTER TABLE "CF_GRUPO" ADD FOREIGN KEY ("COD_GRUPO_PAI") REFERENCES CF_GRUPO ("COD_GRUPO");

/* 20 de Outubro de 2003 */
ALTER TABLE CF_CEDENTE ADD "MENSALIDADE_SERV" VARCHAR(1);

/* 12 de Novembro de 2003 */
ALTER TABLE GC_CLIENTE ADD "CCM_CLI"  VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "IEST_CLI" VARCHAR(20);

/* 25 de Novembro de 2003 */
alter table "CF_SERVICO" ADD "TIPO_SERV" VARCHAR(1);
UPDATE "CF_SERVICO" SET TIPO_SERV = 'C' WHERE TIPO_SERV IS NULL;

/* 10 de Dezembro de 2003 */
alter table "CF_MOVIMENTO_ITENS" ADD "INCIDE_IR_ITEM" VARCHAR(1);

/* 12 de Dezembro de 2003 */
alter table "CF_MOVIMENTO" ADD "VALOR_IR_MOV" DOUBLE PRECISION;

/* 12 de Janeiro de 2004 */
ALTER TABLE "GC_CLIENTE"   ADD "VALOR_ANT"    DOUBLE PRECISION;

/* 03 de FEVEREIRO de 2004 */
alter table "CF_CEDENTE" ADD "CODIGO_CEDENTE_BANCO" VARCHAR(20);

/* 11 de FEVEREIRO de 2004 */
alter table "GC_CLIENTE" ADD "RET_PIS"      VARCHAR(1);
alter table "GC_CLIENTE" ADD "RET_COFINS"	  VARCHAR(1);
alter table "GC_CLIENTE" ADD "RET_CSOCIAL"	VARCHAR(1);

UPDATE "GC_CLIENTE" SET RET_PIS = 'S' WHERE RET_PIS IS NULL;
UPDATE "GC_CLIENTE" SET RET_COFINS = 'S' WHERE RET_COFINS IS NULL;
UPDATE "GC_CLIENTE" SET RET_CSOCIAL = 'S' WHERE RET_CSOCIAL IS NULL;

/* 11 de MARÇO de 2004 */
alter table "GC_DOCUMENTO" ADD "TIPO_VENCTO"      VARCHAR(1);
CREATE TABLE "GC_OBRIGACOES"
(
  "COD_OBR"	    NUMERIC(9, 0) NOT NULL,
  "ANOMES_OBR"	VARCHAR(6)    NOT NULL,
  "COD_CLIENTE" NUMERIC(9, 0) NOT NULL,
  "COD_DOCTO"   NUMERIC(9, 0),
  "DT_VENCTO"	  TIMESTAMP,
  "DT_ENVIO"	  TIMESTAMP,
  "MEIO_ENVIO"  VARCHAR(1),
  "VALOR_DOCTO" DOUBLE PRECISION,
 PRIMARY KEY ("COD_OBR", "ANOMES_OBR", "COD_CLIENTE")
);
ALTER TABLE "GC_OBRIGACOES" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");
ALTER TABLE "GC_OBRIGACOES" ADD FOREIGN KEY ("COD_DOCTO") REFERENCES GC_DOCUMENTO ("COD_DOCTO");

CREATE TABLE "GC_FERIADO"
(
  "DT_FERIADO"	  TIMESTAMP   NOT NULL,
  "DESC_FERIADO"	VARCHAR(30),
 PRIMARY KEY ("DT_FERIADO")
);

/* 15 de MARÇO de 2004 */
alter table "GC_DOCUMENTO" ADD "GERA_AGENDA"      VARCHAR(1);
ALTER TABLE "GC_CLIENTE"   ADD "DATA_FIM_CLI"     TIMESTAMP;

/* 18 de MARÇO de 2004 */
ALTER TABLE "GC_CLIENTE"   ADD "TAXA_BANCARIA_CLI" VARCHAR(1);
UPDATE "GC_CLIENTE"   SET TAXA_BANCARIA_CLI = 'S' WHERE TAXA_BANCARIA_CLI IS NULL;


/* 20 de MARÇO de 2004 */
ALTER TABLE "GC_FICHA"     ALTER "OBS"             TYPE    VARCHAR(1000);
ALTER TABLE "GC_FICHA_AND" ALTER "DESC_ANDAMENTO"  TYPE    VARCHAR(1000);
ALTER TABLE "GC_CLIENTE"   ADD "TAXA_BANCARIA_CLI" VARCHAR(1);
UPDATE "GC_CLIENTE"   SET TAXA_BANCARIA_CLI = 'S' WHERE TAXA_BANCARIA_CLI IS NULL;

/* 22 de MARÇO de 2004 */
CREATE TABLE CF_IMPOSTO (
    ANOMES_IMPOSTO        VARCHAR(6) NOT NULL,
    COD_IMPOSTO           INTEGER NOT NULL,
    COD_CLIENTE           INTEGER NOT NULL,
    NOME_IMPOSTO          VARCHAR(30),
    BASE_IMPOSTO          DOUBLE PRECISION,
    VALOR_IMPOSTO         DOUBLE PRECISION,
    DESCONTO_IMPOSTO      DOUBLE PRECISION,
    JUROS_IMPOSTO         DOUBLE PRECISION,
    MULTA_IMPOSTO         DOUBLE PRECISION,
    DT_EMISSAO_IMPOSTO    TIMESTAMP,
    DT_VENCTO_IMPOSTO     TIMESTAMP,
    DESCRICAO_IMPOSTO     VARCHAR(200),
    DT_APURACAO_IMPOSTO   TIMESTAMP,
    ALIQ_IMPOSTO          DOUBLE PRECISION,
    VALOR_IMPANT_IMPOSTO  DOUBLE PRECISION,
    DT_PAGTO_IMPOSTO      TIMESTAMP,
    MODULO_IMPOSTO        VARCHAR(15),
    DCTF_IMPOSTO          VARCHAR(1),
    COD_USU               INTEGER,
    VARIACAO_IMPOSTO      INTEGER,
    CONFERIDO_IMPOSTO     VARCHAR(1),
    OBS_IMPOSTO           VARCHAR(40),
 PRIMARY KEY ("ANOMES_IMPOSTO", "COD_IMPOSTO", "COD_CLIENTE")
);
ALTER TABLE "CF_MOVIMENTO_ITENS"   ALTER "COMPL_HISTORICO" TYPE VARCHAR(50);

/* 27 de ABRIL de 2004 */
ALTER TABLE GC_LIGACAO ALTER "DESC_LIG" TYPE VARCHAR(1000);
ALTER TABLE GC_LIGACAO ALTER "OBS_LIG" TYPE VARCHAR(1000);

/* 04 de MAIO de 2004 */
ALTER TABLE "GC_LIVRO_OCORRENCIA" ADD "QTD_LIVRO"    NUMERIC(9,0);
ALTER TABLE "GC_LIVRO_OCORRENCIA" ADD "VALOR_LIVRO"  DOUBLE PRECISION;
ALTER TABLE "GC_LIVRO"            ADD "VALOR1_LIVRO" DOUBLE PRECISION;
ALTER TABLE "GC_LIVRO"            ADD "VALOR2_LIVRO" DOUBLE PRECISION;
ALTER TABLE "GC_LIVRO"            ADD "VALOR3_LIVRO" DOUBLE PRECISION;
ALTER TABLE "GC_LIVRO"            ADD "VALOR4_LIVRO" DOUBLE PRECISION;

/* 07 de MAIO de 2004 */
ALTER TABLE "GC_CLIENTE" ADD "QTD_FUNC"        NUMERIC(9,0);
ALTER TABLE "GC_CLIENTE" ADD "QTD_NF"          NUMERIC(9,0);
ALTER TABLE "GC_CLIENTE" ADD "QTD_LANCTO_CTB"  NUMERIC(9,0);

/* 19 de MAIO de 2004 */
CREATE TABLE "CF_OBS_CLIENTE"
(
  "COD_CLIENTE" NUMERIC(9, 0) NOT NULL,
  "COD_OBS_CLI" NUMERIC(9, 0) NOT NULL,
  "DT_OBS_CLI"  TIMESTAMP,
  "OBS_CLI"     VARCHAR(1000),
  PRIMARY KEY ("COD_CLIENTE", "COD_OBS_CLI")
);
ALTER TABLE "CF_OBS_CLIENTE" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");

/* 21 de MAIO de 2004 */
ALTER TABLE "GC_DEPARTAMENTO" ADD "CUSTO_DEPTO" DOUBLE PRECISION;
ALTER TABLE "GC_DEPARTAMENTO" ADD "TIPO_DEPTO"  VARCHAR(1);

/* 01 de JUNHO de 2004 */
CREATE TABLE "GC_CLIENTE_REL"
(
  "COD_CLIENTE" NUMERIC(9, 0) NOT NULL,
  "COD_CLI_REL" NUMERIC(9, 0) NOT NULL,
  PRIMARY KEY ("COD_CLIENTE", "COD_CLI_REL")
);
ALTER TABLE "GC_CLIENTE_REL" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");
ALTER TABLE "GC_CLIENTE_REL" ADD FOREIGN KEY ("COD_CLI_REL") REFERENCES GC_CLIENTE ("COD_CLIENTE");

ALTER TABLE "GC_CLIENTE"     ADD "RET_IRRF"	VARCHAR(1);
UPDATE "GC_CLIENTE" SET RET_IRRF = 'S' WHERE RET_IRRF IS NULL;

/* 16 de JUNHO de 2004 */
ALTER TABLE "GC_CLIENTE"     ADD "ANOMES_APU_INI"	VARCHAR(6);
ALTER TABLE "GC_CLIENTE"     ADD "ANOMES_APU_FIN"	VARCHAR(6);

/* 18 de JUNHO de 2004 */
ALTER TABLE "GC_CLIENTE"     ADD "PAGINA_GUIA"	VARCHAR(10);
ALTER TABLE "GC_CLIENTE"     ADD "COD_SETOR"	  NUMERIC(9,0);

CREATE TABLE "GC_SETOR"
(
  "COD_SETOR"   NUMERIC(9, 0) NOT NULL,
  "DESC_SETOR"  VARCHAR(50),
  "GERA_PROTO"  VARCHAR(1),
  PRIMARY KEY ("COD_SETOR")
);

ALTER TABLE "GC_PROTOCOLO"     ADD "ASSINATURA_PROTO"	BLOB SUB_TYPE 0 SEGMENT SIZE 80;

/* 24 de JUNHO de 2004 */
ALTER TABLE "CF_MOVIMENTO_ITENS" ALTER "COMPL_ITEM" TYPE VARCHAR(50);

/* 28 de JUNHO de 2004 */
ALTER TABLE GC_LIGACAO ADD "PARTICULAR_LIG" VARCHAR(1);
ALTER TABLE GC_LIGACAO ADD "COD_ASSUNTO"    NUMERIC(9,0);

CREATE TABLE "GC_ASSUNTO"
(
  "COD_ASSUNTO"   NUMERIC(9, 0) NOT NULL,
  "DESC_ASSUNTO"  VARCHAR(250),
  PRIMARY KEY ("COD_ASSUNTO")
);
ALTER TABLE GC_ASSUNTO ADD "COD_DEPTO" NUMERIC(9,0);

/*ALTER TABLE GC_LIGACAO DROP "tipo_ligacao";*/
ALTER TABLE GC_LIGACAO ADD "TIPO_LIGACAO" VARCHAR(1);

/* 05 de JULHO de 2004 */
ALTER TABLE GC_ASSUNTO ADD "CLASSIFIC_ASSUNTO" VARCHAR(10);

/* 13 de JULHO de 2004 */
CREATE TABLE "CF_CONFIG_SERV"
(
  "COD_CONFIG"    NUMERIC(9, 0) NOT NULL,
  "COD_SERV_IR"   NUMERIC(9,0),
  "COD_SERV_RET"  NUMERIC(9,0),
  "COD_SERV_MENS" NUMERIC(9,0),
  PRIMARY KEY ("COD_CONFIG")
);
ALTER TABLE "CF_CONFIG_SERV" ADD "VALOR_PISO_IR" DOUBLE PRECISION;
ALTER TABLE "CF_CONFIG_SERV" ADD "ALIQ_IR" DOUBLE PRECISION;

ALTER TABLE GC_CLIENTE   ADD "CAPITAL_SOCIAL"     DOUBLE PRECISION;
ALTER TABLE GC_CLIENTE   ADD "INTEGRALIZADO"      DOUBLE PRECISION;
ALTER TABLE GC_CLIENTE   ADD "A_INTEGRALIZAR"     DOUBLE PRECISION;
ALTER TABLE GC_CLIENTE   ADD "OBJETO_SOCIAL"      VARCHAR(250);
ALTER TABLE GC_CLIENTE   ADD "GERENCIA"           VARCHAR(1);
ALTER TABLE GC_CLIENTE   ALTER "CONTATO_CLI"      TYPE VARCHAR(30);
ALTER TABLE GC_CLIENTE   ADD "PRAZO"              VARCHAR(30);
ALTER TABLE GC_CLIENTE   ADD "FORMA_INTEGRALIZAR" VARCHAR(1);
ALTER TABLE GC_CLIENTE   ADD "BENS"               VARCHAR(255);
ALTER TABLE GC_CLIENTE   ADD "ORGAO1"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO2"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO3"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO4"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO5"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO6"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO7"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "ORGAO8"             VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "SIGLA_CONSELHO"     VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "TRIBUTACAO"         VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "PREFEITURA"         VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "OUTRA_TRIB"         VARCHAR(20);
ALTER TABLE GC_CLIENTE   ADD "VALOR_ANT" DOUBLE PRECISION;
ALTER TABLE GC_CLIENTE   ADD "OBS_CLI" VARCHAR(400);
ALTER TABLE GC_CLIENTE   ADD "TIPO_TRIB_CLI" VARCHAR(1);
ALTER TABLE GC_ATENDIMENTO_PARC ADD "ENVIA_MEMO" VARCHAR(1);
UPDATE GC_ATENDIMENTO_PARC SET ENVIA_MEMO='N' WHERE ENVIA_MEMO IS NULL;
ALTER TABLE GC_CLIENTE ADD "DIAMES_DECIMO_CLI" VARCHAR(4);

/* 14 de JULHO de 2004 */
ALTER TABLE "GC_DOCUMENTO_EMITIDO" ALTER "OBS_DOCTO_EMI" VARCHAR(50);

/* 22 de JULHO de 2004 */
CREATE TABLE "GC_ENTRADA_DOC"
(
  "COD_ENTRADA"    NUMERIC(9, 0) NOT NULL,
  "COD_CLIENTE"    NUMERIC(9, 0) NOT NULL,
  "DT_ENTRADA"     TIMESTAMP,
  "DT_RETORNO"     TIMESTAMP,
  "ANOMES_COMPET"  VARCHAR(6),
  "COD_DOCTO"      NUMERIC(9, 0),
  "COMPL_DOCTO"    VARCHAR(250),
  "COD_DEPTO"      NUMERIC(9, 0),
  "OCORRECIA_ENT"  VARCHAR(1000),
  "COD_FUNC"       NUMERIC(9, 0),
  PRIMARY KEY ("COD_ENTRADA","COD_CLIENTE")
);
ALTER TABLE "GC_ENTRADA_DOC" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");
ALTER TABLE "GC_ENTRADA_DOC" ADD FOREIGN KEY ("COD_DOCTO") REFERENCES GC_DOCUMENTO ("COD_DOCTO");
ALTER TABLE "GC_ENTRADA_DOC" ADD FOREIGN KEY ("COD_DEPTO") REFERENCES GC_DEPARTAMENTO ("COD_DEPTO");
ALTER TABLE "GC_ENTRADA_DOC" ADD FOREIGN KEY ("COD_FUNC") REFERENCES GC_FUNCIONARIO ("COD_FUNC");

/* 01 de AGOSTO de 2004 */
ALTER TABLE GC_ATENDIMENTO ADD "COD_ASSUNTO"    NUMERIC(9,0);

/*12 de AGOSTO de 2004*/
ALTER TABLE "CF_CONFIG_SERV" ADD "COD_SERV_CB"  NUMERIC(9,0);

/*20 de AGOSTO de 2004*/
ALTER TABLE "GC_FUNCIONARIO" ADD "VER_VALORES"   VARCHAR(1);
ALTER TABLE "GC_FUNCIONARIO" ADD "RAMAL_FUNC"    VARCHAR(5);
ALTER TABLE "GC_FUNCIONARIO" ADD "DT_NASCIMENTO" TIMESTAMP;
UPDATE GC_FUNCIONARIO SET VER_VALORES = 'S' WHERE VER_VALORES IS NULL;
ALTER TABLE "GC_OBRIGACOES" ADD "OBS_OBRIGACAO"  VARCHAR(1000);

/*26 de AGOSTO de 2004*/
ALTER TABLE "GC_ATENDIMENTO_PARC" ADD "DT_PAGTO_PARC" TIMESTAMP;

/* 05 de OUTUBRO de 2004 */
ALTER TABLE "GC_CLIENTE" ADD "QTD_FUNC2"        NUMERIC(9,0);
ALTER TABLE "GC_CLIENTE" ADD "QTD_NF2"          NUMERIC(9,0);
ALTER TABLE "GC_CLIENTE" ADD "QTD_LANCTO_CTB2"  NUMERIC(9,0);

/* 13 de OUTUBRO de 2004 */
ALTER TABLE "GC_CLIENTE" ADD "PAGA13_CLI"	      VARCHAR(1);
UPDATE "GC_CLIENTE" SET PAGA13_CLI = 'S'   WHERE PAGA13_CLI IS NULL;
ALTER TABLE "GC_CLIENTE" ADD "PROTESTA_CLI"	    VARCHAR(1);
UPDATE "GC_CLIENTE" SET PROTESTA_CLI = 'S' WHERE PROTESTA_CLI IS NULL;

CREATE TABLE "GC_MENSALIDADE_CLI"
(
  "COD_CLIENTE"       NUMERIC(9, 0) NOT NULL,
  "DT_ALTERACAO"      TIMESTAMP NOT NULL,
  "VALOR_MENSALIDADE" DOUBLE PRECISION,
  PRIMARY KEY ("COD_CLIENTE","DT_ALTERACAO")
);
ALTER TABLE "GC_MENSALIDADE_CLI" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");

ALTER TABLE gc_cliente ALTER "OBS_CLI" TYPE VARCHAR(1000);
ALTER TABLE "GC_TAXA" ADD "QTDE_BENS"	    NUMERIC(9,0);

ALTER TABLE "CF_MOVIMENTO" ALTER "COMPL_HISTORICO" TYPE VARCHAR(50);
ALTER TABLE "CF_MOVIMENTO" ADD   "ANOMES_MOVTO" VARCHAR(6);

/* 14 de OUTUBRO de 2004 */
ALTER TABLE "CF_MOVIMENTO" ADD "TIPO_BAIXA_MOVTO"	VARCHAR(1);
ALTER TABLE "CF_MOVIMENTO" ADD "TIPO_COB_MOVTO"	VARCHAR(1);

/* 29 de NOVEMBRO de 2004 */
alter table "GC_CLIENTE" ADD "RET_13"      VARCHAR(1);
alter table "GC_CLIENTE" ADD "RET_IR_13"   VARCHAR(1);

/* 01 de FEVEREIRO de 2005 */
alter table gc_atendimento ALTER "DESCRICAO_ATEND" TYPE VARCHAR(3000);


/* 30 Março de 2005 */
alter table "GC_CLIENTE" ADD "COD_CONTA" VARCHAR(10);

/* 15 de ABRIL de 2004 */
ALTER TABLE GC_VISITA      ADD "COD_ATENDIMENTO" NUMERIC(9,0);
ALTER TABLE GC_MEMORANDO   ADD "COD_ATENDIMENTO" NUMERIC(9,0);

/* 22 de ABRIL de 2005 */
ALTER TABLE GC_CLIENTE ADD "ENDERECO_DOC_CLI" VARCHAR(50);
ALTER TABLE GC_CLIENTE ADD "BAIRRO_DOC_CLI"   VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "CIDADE_DOC_CLI"   VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "UF_DOC_CLI"       VARCHAR(2);
ALTER TABLE GC_CLIENTE ADD "CEP_DOC_CLI"      VARCHAR(9);

/* 28 de ABRIL de 2005 */
CREATE TABLE GC_LEMBRETE(
    COD_AGENDA       NUMERIC(9, 0) NOT NULL,
    COD_FUNC         NUMERIC(9, 0) NOT NULL,
    ASSUNTO_AGENDA   VARCHAR(100),
    RELATO_AGENDA    BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    DT_AGENDA        TIMESTAMP,
    DT_MOSTRA_AGENDA TIMESTAMP,
    STATUS_AGENDA    VARCHAR(1),
    DT_FECHA_AGENDA  TIMESTAMP,
    PRIMARY KEY (COD_AGENDA, COD_FUNC)
);

/* 03 de JUNHO de 2005 */
ALTER TABLE GC_VISITA ALTER "OBS_VISITA" TYPE VARCHAR(1000);

/* 06 de Junho 2005 */
CREATE TABLE CON_CONFIGURA (
    RAZAO_CON         VARCHAR(70) NOT NULL,
    ENDERECO_CON      VARCHAR(60),
    BAIRRO_CON        VARCHAR(20),
    CEP_CON           VARCHAR(9),
    CIDADE_CON        VARCHAR(20),
    ESTADO_CON        VARCHAR(2),
    EMAIL_CON         VARCHAR(50),
    TIPO_PESSOA_CON   VARCHAR(1),
    CPFCNPJ_CON       VARCHAR(14),
    FONE1_CON         VARCHAR(15),
    FONE2_CON         VARCHAR(15),
    FONE3_CON         VARCHAR(15),
    FONE4_CON         VARCHAR(15),
    FAX_CON           VARCHAR(15),
    FISCAL_CON        VARCHAR(1),
    CONTABIL_CON      VARCHAR(1),
    FOLHA_CON         VARCHAR(1),
    MASCARAPLANO_CON  VARCHAR(20),
    SPOOL_CON         VARCHAR(1),
    QTDE_USUARIO      INTEGER
);

/* 10 de Junho 2005 */
alter table gc_protocolo alter "OBS_PROTOCOLO" type varchar(1000);
ALTER TABLE GC_AGENDA ADD "COD_CLIENTE" NUMERIC(9,0);

/* 24 de Junho 2005 */
alter table GC_PROTOCOLO ADD "COD_ATENDIMENTO" NUMERIC(9,0);
alter table seg_libera add "STATUS" VARCHAR(1);

/* 27 de Dezembro 2005 */
alter table GC_ENTRADA_DOC ADD "CONTA_DEBITO"  NUMERIC(9,0);
alter table GC_ENTRADA_DOC ADD "CONTA_CREDITO" NUMERIC(9,0);
alter table GC_ENTRADA_DOC ADD "VALOR_DOCTO"   DOUBLE PRECISION;
alter table GC_LEMBRETE    ADD "COD_USU_CAD"      NUMERIC(9, 0);

/* 18 de Abril 2006 */
ALTER TABLE GC_CLIENTE ADD "COD_USU_CTB"  NUMERIC(9,0);
ALTER TABLE GC_CLIENTE ADD "COD_USU_FIS"  NUMERIC(9,0);
ALTER TABLE GC_CLIENTE ADD "COD_USU_FOL"  NUMERIC(9,0);
ALTER TABLE GC_VISITA ADD "RESUMO_RELATO" VARCHAR(100);
