ALTER TABLE GC_FICHA ADD "COD_DEPTO" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD "COD_FUNC" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD "PREFEITURA" VARCHAR(20);

ALTER TABLE GC_FICHA ADD "ORGAO1_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO2_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO3_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO4_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO5_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO6_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO7_PROC" VARCHAR(1000);
ALTER TABLE GC_FICHA ADD "ORGAO8_PROC" VARCHAR(1000);

ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_DEPTO") REFERENCES GC_DEPARTAMENTO;
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_FUNC") REFERENCES GC_FUNCIONARIO;

ALTER TABLE GC_FICHA_SOC ALTER "ENDERECO" TYPE VARCHAR(100);
ALTER TABLE GC_FICHA_SOC ADD "SEXO" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "ORGAO_NUMERO" VARCHAR(30);
ALTER TABLE GC_FICHA_SOC ADD "PROCURADOR" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "SITUACAO_SOC" VARCHAR(1);

ALTER TABLE GC_VISITA ADD "TIPO_COMPROMISSO" VARCHAR(1);

ALTER TABLE GC_PROTOCOLO ADD "COD_FUNC_CAD" NUMERIC(9,0);
ALTER TABLE GC_PROTOCOLO ADD FOREIGN KEY ("COD_FUNC_CAD") REFERENCES GC_FUNCIONARIO ("COD_FUNC");

ALTER TABLE GC_DOCUMENTO_EMITIDO ADD "DT_VENCIMENTO" TIMESTAMP;


ALTER TABLE GC_VISITA  ADD "DETALHE_VISTA" VARCHAR(1000);
ALTER TABLE GC_LIGACAO ADD "TIPO_LIGACAO" VARCHAR(1);
DROP TRIGGER "TRI_GEN_ATEND";

/* 26 de agosto 2002 */
ALTER TABLE "GC_CLIENTE"   ADD "NIVEL_CLI" VARCHAR(1);
ALTER TABLE GC_CLIENTE ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_CLIENTE ADD "COD_CONTA"	VARCHAR(10);
ALTER TABLE GC_CLIENTE ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_CLIENTE ADD FOREIGN KEY ("COD_CONTA") REFERENCES CF_CONTA ("COD_CONTA");

ALTER TABLE GC_DOCUMENTO ADD "COD_SERV"	NUMERIC(9,0);
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_SERV") REFERENCES CF_SERVICO ("COD_SERV");

ALTER TABLE GC_DOCUMENTO ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_DOCUMENTO ADD "COD_CONTA"   VARCHAR(10);
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_DOCUMENTO ADD FOREIGN KEY ("COD_CONTA")   REFERENCES CF_CONTA ("COD_CONTA");

/* 28 de agosto 2002 */
CREATE TABLE "GC_FICHA_PAG"
(
  "COD_FICHA"	   NUMERIC(9, 0) NOT NULL,
  "COD_PAG"        NUMERIC(9, 0) NOT NULL,
  "DT_PREV_PAG"    TIMESTAMP,
  "DT_PAG"         TIMESTAMP,
  "VALOR_PAG"	   DOUBLE PRECISION,
  PRIMARY KEY ("COD_FICHA", "COD_PAG")
);
ALTER TABLE "GC_FICHA_PAG" ADD FOREIGN KEY ("COD_FICHA") REFERENCES GC_FICHA ("COD_FICHA");

ALTER TABLE GC_FICHA ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_FICHA ADD "COD_CONTA"   VARCHAR(10);
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_PLCONTA") REFERENCES CF_PLANO_CONTA ("COD_PLCONTA");
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_CONTA")   REFERENCES CF_CONTA ("COD_CONTA");

/* 29 de agosto 2002 */
ALTER TABLE GC_DOCUMENTO ADD "COD_PLCONTA" NUMERIC(9, 0);
ALTER TABLE GC_CLIENTE ADD "TIPO_CLIFOR" VARCHAR(1);

/* 03 de Setembro */
ALTER TABLE GC_FICHA ADD "COD_CLIENTE" NUMERIC(9,0);
ALTER TABLE GC_FICHA ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE;

/* 04 de Outubro */
ALTER TABLE GC_FUNCIONARIO ADD "ATIVO_FUNC" VARCHAR(1);

/* 30 de Outubro */
ALTER TABLE GC_ATENDIMENTO ADD "EMAIL_ATEND" VARCHAR(1);
ALTER TABLE GC_ATENDIMENTO ADD "COBRA_ATEND" VARCHAR(1);

/* 12 DE NOVEMBRO */
/*alter table GC_VISITA DROP "COD_CLIENTE";*/
alter table GC_VISITA add "COD_CLIENTE" numeric(9,0);
ALTER TABLE "GC_VISITA" ADD FOREIGN KEY ("COD_CLIENTE") REFERENCES GC_CLIENTE ("COD_CLIENTE");

/* 20 DE NOVEMBRO */
ALTER TABLE GC_FICHA_SOC ADD "NUM_INSS_SOC" VARCHAR(20);
ALTER TABLE GC_FICHA_SOC ADD "TEMPO_INSS_SOC" VARCHAR(20);
ALTER TABLE GC_FICHA_SOC ADD "CONTRIB_ATU_INSS" VARCHAR(1);
ALTER TABLE GC_FICHA_SOC ADD "NUM_PIS_SOC" VARCHAR(20);

/* 26 DE NOVEMBRO */
ALTER TABLE GC_ATENDIMENTO ADD "RELATO_CLIENTE" BLOB;
ALTER TABLE GC_ATENDIMENTO ADD "DT_PREV_FECHA" TIMESTAMP;

/* 27 DE NOVEMBRO */
ALTER TABLE GC_ATENDIMENTO ADD "INFORMADO_ATEND" VARCHAR(1);
ALTER TABLE GC_VISITA ADD "INFORMADO_VIS" VARCHAR(1);
ALTER TABLE GC_LIGACAO ADD "INFORMADO_LIG" VARCHAR(1);

UPDATE GC_ATENDIMENTO SET INFORMADO_ATEND='N';
UPDATE GC_VISITA      SET INFORMADO_VIS='N';
UPDATE GC_LIGACAO     SET INFORMADO_LIG='N';

/* 21 DE DEZEMBRO 2003*/
ALTER TABLE GC_FUNCIONARIO ADD "DT_NASCIMENTO" TIMESTAMP;

/* 20 DE MARÇO 2003*/
ALTER TABLE GC_CLIENTE ADD "BAIRRO_COB_CLI" VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "CIDADE_COB_CLI" VARCHAR(20);
ALTER TABLE GC_CLIENTE ADD "UF_COB_CLI"     VARCHAR(2);
ALTER TABLE GC_CLIENTE ADD "CEP_COB_CLI"    VARCHAR(9);
ALTER TABLE GC_CLIENTE ADD "CORRESPONDENCIA_CLI" VARCHAR(1);

/* 30 DE MARÇO 2003*/
ALTER TABLE GC_CLIENTE   ADD "TIPO_TAXA_CLI"  VARCHAR(1);
ALTER TABLE GC_CLIENTE   ADD "VALOR_TAXA_CLI" DOUBLE PRECISION;
ALTER TABLE GC_DOCUMENTO ADD "DATA_VENCTO_DOCTO" TIMESTAMP;

/* 02 DE JULHO 2003*/
ALTER TABLE GC_CLIENTE   ADD "MES_REF_CLI"  VARCHAR(6);
ALTER TABLE GC_CLIENTE   ADD "DATA_INICIO_CLI"  TIMESTAMP;

/* 11 DE JULHO 2003*/
CREATE TABLE "GC_ATENDIMENTO_PARC"
(
  "COD_ATENDIMENTO"	NUMERIC(9, 0) NOT NULL,
  "COD_CLIENTE"	    NUMERIC(9, 0) NOT NULL,
  "COD_PARCELA"	    NUMERIC(9, 0) NOT NULL,
  "COD_FUNC"	      NUMERIC(9, 0),
  "DT_VENCTO_PARC"	TIMESTAMP,
  "VALOR_PARC"      DOUBLE PRECISION,
  "OBS_PARC"	      VARCHAR(255),
  PRIMARY KEY ("COD_ATENDIMENTO","COD_CLIENTE","COD_PARCELA")
);
ALTER TABLE "GC_OCORRENCIA" ADD FOREIGN KEY ("COD_FUNC") REFERENCES GC_FUNCIONARIO;
ALTER TABLE "GC_OCORRENCIA" ADD FOREIGN KEY ("COD_ATENDIMENTO", "COD_CLIENTE") REFERENCES GC_ATENDIMENTO ("COD_ATENDIMENTO", "COD_CLIENTE");

/* 23 DE JUNHO 2003 */
ALTER TABLE GC_CLIENTE ADD "SENHA_INT" VARCHAR(15);

/* 10 DE JULHO 2003 */
ALTER TABLE "GC_DOCUMENTO_EMITIDO" ADD "VALOR_DOCTO_EMI" DOUBLE PRECISION;

/* 07 DE AGOSTO 2003 */
ALTER TABLE "GC_PROTOCOLO" ADD "RESPONSAVEL_PROTO" VARCHAR(30);

/* 27 DE AGOSTO 2003 */
ALTER TABLE "GC_FUNCIONARIO" ADD "RAMAL_FUNC" VARCHAR(5);

